### ISSUE TITLE
`Error: cannot find artifact ` when multiple artifacts found

### ISSUE THREAD

**Issue by SvineruS** [wighawag/hardhat-deploy#173]
You ignore exception here
https://github.com/wighawag/hardhat-deploy/blob/d91ca1ec6d7f043fbe23af6b98584dc469603407/src/utils.ts#L38-L40

and throw `cannot find artifact`
https://github.com/wighawag/hardhat-deploy/blob/d91ca1ec6d7f043fbe23af6b98584dc469603407/src/DeploymentsManager.ts#L195-L197

however inner call can throw MULTIPLE_FOUND, not just NOT_FOUND
https://github.com/nomiclabs/hardhat/blob/2c94722f86d721d45634aed58ee30b7cebad8184/packages/hardhat-core/src/internal/artifacts.ts#L390-L404

**Comment by kylebakerio** [comment]
wow, just had this issue. this could have gotten me _very_ stuck, thanks a ton for this bug report.

**Comment by starlabs007** [comment]
Are there any workarounds? I'm trying to deploy flattened contracts and I'm getting `cannot find artifact`.

**Comment by kylebakerio** [comment]
Oh, this was an obvious flag to me that I had two contracts with the same name. So, two artifacts were getting created that clashed.

I don't know what the cause is in your case, but check your artifacts folder and look for duplicates, or check your contracts and make sure there are no name collisions. If truly stuck, consider using `git bisect`.

**Comment by starlabs007** [comment]
Thanks, I found a workaround. It involves manually specifying the artifact paths, as per [deploy instructions here](https://github.com/wighawag/hardhat-deploy#importing-deployment-from-other-projects-with-truffle-support).

**Comment by wighawag** [comment]
in hardhat-deploy 0.9.20 I made the hardhat error for multilple artifact found comes through
