### ISSUE TITLE
add "dry-run" feature

### ISSUE THREAD

**Issue by drortirosh** [wighawag/hardhat-deploy#244]
The tool does an excellent job deploying only what needs to deploy.
e.g. I can "alomst" re-run deploy, just to generate `--export-all`, knowing it will not modify anything.

it is "almost", since I can't make certain it won't attempt to re-deploy".

Please add `--dry-run` or `--no-deploy` param, that would run the script, but will not attempt an actual deployment, just for local side-effects of the script.

**Comment by wighawag** [comment]
Hey @drortirosh I personnly use fork for exactly this.

The issue with dry-run without fork is that it cannot work past the first tx if the 2nd tx depends on the first

Using fork requirse some setup (due to how fork settings work in hardhat) but it not too hard,  see in this repo for an example: https://github.com/wighawag/template-ethereum-contracts/blob/main/README.md#yarn-forkdeploy-network---blocknumber-blocknumber-args

It actually work great as you can test the real operation, see their gas cost, etc....
