### ISSUE TITLE
Confusing behavior when running `buidler node` vs. `buidler deploy` with no args

### ISSUE THREAD

**Issue by blakewest** [wighawag/hardhat-deploy#39]
I noticed today that if I run `npx buidler node` with no args, then it will run my deployment scripts and save the output to a folder called `localhost_31337`, which seems correct. But if I do the same with `npx buidler deploy`, then nothing is saved. I find this pretty confusing, and it caused me some headaches. I realized if I do `npx buidler deploy --network localhost` then I get the behavior I was expecting. I just didn't think I would have to do this. 

I see the README says `Note that running buidler deploy without specifying a network will use the default network. If the default network is an internal ganache or buidlerevm then nothing will happen as a result but this can be used to ensure the deployment is without issues.`. I read this and assumed that "default network" would be `localhost`, and so having to explicitly say `--network localhost` would be unnecessary. Perhaps that's not correct?

My expectation would be that `npx buidler deploy` and `npx buidler node` would produce the same result, except that `deploy` would not keep the network going the way that `node` does, and so making the behavior the same would be my preference. If you think this discrepancy is correct though, then I think this could be cleared up in the README by saying something like, "running buidler deploy without any network will not save any deployments, and nor will it use any previously saved deployments. You must specify a network to get this behavior"

**Comment by wighawag** [comment]
hi @blakewest Thanks for the feedback

Note that the default network is a buidler thing, not a buidler-deploy thing
By default the default network is `buidlerevm` that only run in memory, but the default network can be configured to be `localhost`

Now regarding buidler-deploy behavior, it follow buidler configuration. so executing `buidler deploy` act on `buidlerevm` and thus run only in memory and by default do not save to disk (as there is no point)

As for `buidler node` buidler-deploy will also run against buidlerevm network (and so all config associated with buidlerevem in buidler.config.js will be taken in consideration

But buidler-deploy do something special in that it save the deployment as belonging to `localhost` this is because the network running in memory is accessible via localhost and so if you execute a command like `buidler --network console` you will be connected to the network being run by `buidler node` and would expect to have access to the contract deployed there. buidler-deploy make sure you can.

I added a note about that here : https://github.com/wighawag/buidler-deploy#buidler-node

I hope that it clarify your question. I ll try to make it more clear in the doc.

I also wonder whether `buidler node` should have a different behavior in buidler itself.
