### ISSUE TITLE
Handling increases in gas prices during deployment

### ISSUE THREAD

**Issue by smartcontracts** [wighawag/hardhat-deploy#96]
Hello! https://github.com/ethereum-optimism/contracts is now using `hardhat-deploy` for our L1 deployments. We just did an experimental mainnet deployment and ran into some issues with gas prices increasing during the course of execution. Since gas prices increased, the deployment was pretty much stuck until either (1) gas prices decreased again or (2) we restart the deployment and delete `.pendingTransactions` to force `hardhat-deploy` to re-submit the transaction that got stuck.

Option (1) is potentially *very* slow and option (2) feels somewhat unsafe. I think it'd be ideal for `hardhat-deploy` to try to automatically increase the gas price and resubmit if the transaction is stuck for a sufficiently long period of time. 

edit; we tried option (2) but it doesn't work because it tries to use the next nonce (and doesn't clear the previous transaction). Ended up manually clearing the nonce by sending a 0 value tx to ourselves.

**Comment by wighawag** [comment]
Thanks @smartcontracts for the report.

I encountered the same issue for 2) and plan for a fix to use the latest confirmed nonce.
I have also plan to improve pending transaction resolution on restart to let you increase the gas.
This would not be an automatic solution though

Note that I am open to an automatic solution if this is not overly complex

**Comment by wighawag** [comment]
in latest version 0.8.x hardhat-deploy now use the confirmed nonce
I also added pending tx resolution which let you resubmit with hogher gas

**Comment by ameshkin** [comment]
I believe this is why I am having issues deploying.  When I deploy on mainnet, it just kind of hangs.  It's waiting for gas prices to come in line with my settings.

I am not sure what to set my gas prices, and not sure if $150 for my tiny contract seems right on remix.

I will start using hardhat deploy today, instead of my own deploy script. perhaps that will help

What should my gas prices be?  Too low and it could get stuck and I pay. half the gas for an undeployed contract.

Too high and I overpay for a tiny contract
